services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile  # Указываем путь к Dockerfile
    volumes:
      - static_data:/work_task/lazy_ilya/staticfiles  # монтируем staticfiles (STATIC_ROOT)
      - db_sql:/work_task/lazy_ilya/db
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          memory: 256M
    networks:
      - shared_net

  nginx_django:
    image: nginx:alpine
    container_name: nginx_django
    ports:
      - "8000:80"  # на боевом сервере проксируешь через основной Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/work_task/lazy_ilya/staticfiles  # та же папка для статики, чтобы nginx её видел
    depends_on:
      - web
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          memory: 256M
    networks:
      - shared_net

volumes:
  static_data:
  db_sql:

networks:
  shared_net:
    name: shared_net
    external: true