# Generated by Django 5.1.6 on 2025-05-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TableNames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания/обновления"
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название таблицы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Название для таблиц",
                "verbose_name_plural": "Названия для таблиц",
                "ordering": ["pk"],
            },
        ),
    ]
