# Generated by Django 5.1.6 on 2025-05-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания/обновления"
                    ),
                ),
                (
                    "dock_num",
                    models.IntegerField(blank=True, default=9999, verbose_name="№ п/п"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "name_organ",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название органа",
                    ),
                ),
                (
                    "pseudonim",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Псевдоним"
                    ),
                ),
                (
                    "letters",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Письма"
                    ),
                ),
                (
                    "writing",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Записи"
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адрес IP"
                    ),
                ),
                (
                    "some_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Спец номер"
                    ),
                ),
                (
                    "work_timme",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Рабочее время",
                    ),
                ),
                (
                    "table_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.tablenames",
                        verbose_name="Таблица",
                    ),
                ),
            ],
            options={
                "verbose_name": "Таблица городов",
                "verbose_name_plural": "Таблицы городов",
                "ordering": ["pk", "table_id", "dock_num"],
                "unique_together": {("table_id", "dock_num")},
            },
        ),
    ]
