# Generated by Django 5.1.6 on 2025-05-26 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0002_citydata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterCities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания/обновления"
                    ),
                ),
                (
                    "count_responses",
                    models.IntegerField(
                        verbose_name="Количество запросов к этому городу"
                    ),
                ),
                (
                    "dock_num",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.citydata",
                        verbose_name="Пункт в таблице документов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счетчик городов",
                "verbose_name_plural": "Счетчики городов",
                "ordering": ["pk", "dock_num", "count_responses"],
            },
        ),
    ]
