# Generated by Django 5.2.3 on 2025-07-18 19:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_countercities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfoDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания/обновления')),
                ('korr', models.CharField(blank=True, max_length=25, null=True, verbose_name='№ Корреспондента')),
                ('m_b_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер части')),
                ('cipa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер CIPA')),
                ('recipient', models.CharField(blank=True, max_length=255, null=True, verbose_name='Данные получателя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер в международном формате, например: +7 912 345 6789', max_length=128, null=True, region='RU', verbose_name='Телефон')),
                ('ip_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP телефон')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметки')),
                ('globus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.citydata', verbose_name='Номерок в таблице Глобуса')),
            ],
            options={
                'verbose_name': 'Справочник дежурного',
                'verbose_name_plural': 'Справочник дежурного',
                'ordering': ['pk', 'korr', 'm_b_number', 'cipa', 'globus'],
            },
        ),
    ]
