# Generated by Django 4.2.21 on 2025-05-31 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StickyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default="Новая заметка...",
                        verbose_name="Текст заметки",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FFEB3B", max_length=20, verbose_name="Цвет заметки"
                    ),
                ),
                ("position_top", models.FloatField(default=0, verbose_name="Y")),
                ("position_left", models.FloatField(default=0, verbose_name="X")),
                (
                    "author",
                    models.CharField(blank=True, max_length=500, verbose_name="Автор"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sticky_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Таблица стикеров заметок",
                "ordering": ["-created_at"],
            },
        ),
    ]
