# Generated by Django 5.1.6 on 2025-06-20 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stickers", "0002_tag_alter_stickynote_options_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Таблица Тегов"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Таблица задач пользователей"},
        ),
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Название Тега"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Срок исполнения"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="desc",
            field=models.TextField(blank=True, verbose_name="Содержание задачи"),
        ),
        migrations.AlterField(
            model_name="task",
            name="done",
            field=models.BooleanField(
                default=False, verbose_name="Отметка об исполнении"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "\u200d🦼 Низкий"),
                    ("medium", "\u200d🚶\u200d♂️ Средний"),
                    ("high", "🔥🏃\u200d♂️Высокий"),
                ],
                default="medium",
                max_length=10,
                verbose_name="Приоритет задачи",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="stickers.tag", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок задачи"),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления последнего"
            ),
        ),
    ]
