# Generated by Django 5.2.3 on 2025-07-03 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stickers", "0005_alter_stickynote_options_alter_tag_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StickyNoteVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="True — стикер виден пользователю, False — скрыт (удален для себя)",
                        verbose_name="Видимость",
                    ),
                ),
                (
                    "sticky_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibilities",
                        to="stickers.stickynote",
                        verbose_name="Стикер",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sticky_note_visibilities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видимость стикера",
                "verbose_name_plural": "Видимости стикеров",
                "unique_together": {("sticky_note", "user")},
            },
        ),
    ]
