# Generated by Django 5.1.6 on 2025-05-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания/обновления"
                    ),
                ),
                (
                    "num_files",
                    models.IntegerField(verbose_name="Количество обработанных файлов"),
                ),
            ],
            options={
                "verbose_name": "Счетчик сообщений",
                "verbose_name_plural": "Счетчики сообщений",
                "ordering": ["pk"],
            },
        ),
    ]
