# Generated by Django 4.2.9 on 2025-01-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("num_files", models.IntegerField()),
            ],
        ),
    ]
