# Generated by Django 4.2.9 on 2025-02-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SomeTables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("table_name", models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
