# Generated by Django 4.2.9 on 2025-02-02 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0002_sometables"),
    ]

    operations = [
        migrations.CreateModel(
            name="SomeDataFromSomeTables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(max_length=255)),
                ("name_organ", models.CharField(max_length=255)),
                ("pseudonim", models.CharField(max_length=255)),
                ("letters", models.BooleanField(default=False)),
                ("writing", models.BooleanField(default=False)),
                ("ip_address", models.CharField(max_length=255)),
                ("some_number", models.CharField(max_length=255)),
                ("work_timme", models.CharField(max_length=255)),
                (
                    "table_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="work_for_ilia.sometables",
                    ),
                ),
            ],
        ),
    ]
