# Generated by Django 4.2.9 on 2025-02-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0003_somedatafromsometables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="counter",
            options={
                "ordering": ["pk"],
                "verbose_name": "Счетчик сообщений",
                "verbose_name_plural": "Счетчики сообщений",
            },
        ),
        migrations.AlterModelOptions(
            name="somedatafromsometables",
            options={
                "ordering": ["pk"],
                "verbose_name": "Таблица городов",
                "verbose_name_plural": "Таблицы городов",
            },
        ),
        migrations.AlterModelOptions(
            name="sometables",
            options={
                "ordering": ["pk"],
                "verbose_name": "Название для таблиц",
                "verbose_name_plural": "Названия для таблиц",
            },
        ),
        migrations.AlterField(
            model_name="counter",
            name="num_files",
            field=models.IntegerField(verbose_name="Количество обработанных файлов"),
        ),
        migrations.AlterField(
            model_name="counter",
            name="processed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания/обновления"
            ),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="ip_address",
            field=models.CharField(max_length=255, verbose_name="Адрес IP"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="letters",
            field=models.BooleanField(default=False, verbose_name="Письма"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="name_organ",
            field=models.CharField(max_length=255, verbose_name="Название органа"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="processed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания/обновления"
            ),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="pseudonim",
            field=models.CharField(max_length=255, verbose_name="Псевдоним"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="some_number",
            field=models.CharField(max_length=255, verbose_name="Спец номер"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="table_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="work_for_ilia.sometables",
                verbose_name="Таблица",
            ),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="work_timme",
            field=models.CharField(max_length=255, verbose_name="Рабочее время"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="writing",
            field=models.BooleanField(default=False, verbose_name="Записи"),
        ),
        migrations.AlterField(
            model_name="sometables",
            name="processed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания/обновления"
            ),
        ),
        migrations.AlterField(
            model_name="sometables",
            name="table_name",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Название таблицы"
            ),
        ),
    ]
