# Generated by Django 4.2.19 on 2025-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0004_alter_counter_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="somedatafromsometables",
            name="dock_num",
            field=models.IntegerField(null=True, verbose_name="№ п/п"),
        ),
    ]
