# Generated by Django 4.2.19 on 2025-02-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0005_somedatafromsometables_dock_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="dock_num",
            field=models.IntegerField(default=9999, verbose_name="№ п/п"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="ip_address",
            field=models.CharField(max_length=255, null=True, verbose_name="Адрес IP"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="letters",
            field=models.BooleanField(default=False, null=True, verbose_name="Письма"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="location",
            field=models.CharField(max_length=255, null=True, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="name_organ",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название органа"
            ),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="pseudonim",
            field=models.CharField(max_length=255, null=True, verbose_name="Псевдоним"),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="some_number",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Спец номер"
            ),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="work_timme",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Рабочее время"
            ),
        ),
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="writing",
            field=models.BooleanField(default=False, null=True, verbose_name="Записи"),
        ),
    ]
