# Generated by Django 4.2.19 on 2025-02-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0006_alter_somedatafromsometables_dock_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="pseudonim",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Псевдоним"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="somedatafromsometables",
            unique_together={("table_id", "dock_num")},
        ),
    ]
