# Generated by Django 4.2.19 on 2025-02-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0007_alter_somedatafromsometables_pseudonim_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="somedatafromsometables",
            options={
                "ordering": ["pk", "table_id", "dock_num"],
                "verbose_name": "Таблица городов",
                "verbose_name_plural": "Таблицы городов",
            },
        ),
        migrations.AlterField(
            model_name="counter",
            name="processed_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата создания/обновления"
            ),
        ),
    ]
