# Generated by Django 4.2.19 on 2025-02-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0008_alter_somedatafromsometables_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="somedatafromsometables",
            name="pseudonim",
            field=models.CharField(max_length=255, null=True, verbose_name="Псевдоним"),
        ),
    ]
