# Generated by Django 4.2.19 on 2025-02-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0010_alter_somedatafromsometables_dock_num_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterCities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания/обновления"
                    ),
                ),
                (
                    "count_responses",
                    models.IntegerField(
                        verbose_name="Количество запросов к этому городу"
                    ),
                ),
                (
                    "dock_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="work_for_ilia.somedatafromsometables",
                        verbose_name="Пункт в таблице документов",
                    ),
                ),
            ],
        ),
    ]
