# Generated by Django 4.2.19 on 2025-02-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0011_countercities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countercities",
            name="dock_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="work_for_ilia.somedatafromsometables",
                unique=True,
                verbose_name="Пункт в таблице документов",
            ),
        ),
    ]
