# Generated by Django 5.1.6 on 2025-03-03 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_for_ilia", "0012_alter_countercities_dock_num"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countercities",
            options={
                "ordering": ["pk", "dock_num", "count_responses"],
                "verbose_name": "Счетчик городов",
                "verbose_name_plural": "Счетчики городов",
            },
        ),
        migrations.AlterField(
            model_name="countercities",
            name="dock_num",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="work_for_ilia.somedatafromsometables",
                verbose_name="Пункт в таблице документов",
            ),
        ),
    ]
